<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I6EP1Q3" failures="2" tests="10" name="Surefire test" time="10.408" errors="0" timestamp="2023-12-05T21:59:34 EST">
  <testcase classname="api.test.DataDrivenTest" name="testPostUser" time="3.569"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostUser" time="0.573"/>
  <testcase classname="api.test.DataDrivenTest" name="testPostUser" time="0.235"/>
  <testcase classname="api.test.DataDrivenTest" name="testGetUserByName" time="0.461">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTest.testGetUserByName(DataDrivenTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.DataDrivenTest" name="testGetUserByName" time="0.299">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTest.testGetUserByName(DataDrivenTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.DataDrivenTest" name="testGetUserByName" time="0.269"/>
  <testcase classname="api.test.UserTest" name="testPostUser" time="0.27"/>
  <testcase classname="api.test.UserTest" name="testGetUser" time="0.239"/>
  <testcase classname="api.test.UserTest" name="testUpdtaeUser" time="0.482"/>
  <testcase classname="api.test.UserTest" name="testDeleteUser" time="0.226"/>
</testsuite> <!-- Surefire test -->
